### ISSUE TITLE
Action server not avilable!

### ISSUE THREAD

**Issue by aeksiri** [FiorellaSibona/turtlebot3_nav#2]
$ rosrun simple_navigation_goals move_base_seq
[INFO] [1529247654.393390, 0.000000]: [[0.2, 0.5, 0], [2, 0.5, 0], [1.5, -0.5, 0]]
[INFO] [1529247654.399724, 0.000000]: Waiting for move_base action server...
[ERROR] [1529247654.420666, 1673.947000]: Action server not available!

**Comment by antoninovara** [comment]
Hello! @aeksiri,

my name is Antonino and I work as a teacher in a Secondary School.

I'm trying to use turtlebot3_nav with my students and I'm having the same problem that you. Have you found a solution?

Thank you very much!

**Comment by FiorellaSibona** [comment]
> $ rosrun simple_navigation_goals move_base_seq
> [INFO] [1529247654.393390, 0.000000]: [[0.2, 0.5, 0], [2, 0.5, 0], [1.5, -0.5, 0]]
> [INFO] [1529247654.399724, 0.000000]: Waiting for move_base action server...
> [ERROR] [1529247654.420666, 1673.947000]: Action server not available!


Removing the "rospy.Duration(5.0)" paramenter at [line 42](https://github.com/FiorellaSibona/turtlebot3_nav/blob/b8d5c0301bee4e6c503ae9523cc411a31b2eedbd/catkin_ws/src/simple_navigation_goals/scripts/move_base_seq#L42), solves the problem!
